site_name: Computations

docs_dir: docs
hooks:
  - mkdocs_hooks.py

plugins:
  - search
  - gh-admonitions
  - awesome-pages

markdown_extensions:
  - admonition
  - def_list

theme:
  name: material
  features:
    - navigation.indexes
    - navigation.prune

extra_css:
  - assets/vendor/katex.min.css

extra_javascript:
  - assets/vendor/katex.min.js
  - assets/vendor/contrib/auto-render.min.js
  - assets/katex-init.js

extra:
  rust-build:
    enabled: true
    release: false
