[package]
name = "tiny_isa"
version = "0.1.0"
edition = "2024"

[dependencies]
utils = { workspace = true }
pest = { workspace = true }
pest_derive = { workspace = true }
anyhow = { workspace = true }
wasm-bindgen = { workspace = true }
serde = { workspace = true }
