[package]
name = "example_counter"
version = "0.1.0"
edition = "2024"

[dependencies]
utils = { workspace = true }
serde = { workspace = true }
wasm-bindgen = { workspace = true }
serde-wasm-bindgen = { workspace = true }
web_builder = { path = "../../web_builder" }
