[package]
name = "rec_tm_ir"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "rec_tm_ir"
path = "src/bin/rec_tm_ir.rs"

[dependencies]
utils = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
turing_machine = { workspace = true }
