[package]
name = "symbolic_asm"
version = "0.1.0"
edition = "2024"

[dependencies]
utils = { workspace = true }
anyhow = { workspace = true }
wasm-bindgen = { workspace = true }
serde = { workspace = true }

tiny_isa = { path = "../tiny_isa" }
