[book]
authors = ["pdf-jube-joba"]
language = "jp"
src = "src"
title = "computations"

[build]
build-dir = "./out"
create-missing = false
use-default-preprocessors = true

[preprocessor.katex]
inline-delimiter = { left = "\\(", right = "\\)" }
block-delimiter = { left = "\\[", right = "\\]" }
macros = "macros.txt"
no-css = true

[preprocessor.build-assets]
command = "python3 build_assets.py"
build = false
release = false

[output.html]
additional-css = ["src/_assets/style.css", "katex.min.css"]
theme = "theme"
no-section-label = true
hash-files = false
